### ISSUE TITLE
部署连接到QQ没反应，来个大佬看看哪里问题

### ISSUE THREAD

**Issue by qjsir** [LlmKira/Openaibot#261]
openaibot的配置都是按照教程里改的
mirai-http-api的配置是复制教程里的
但启动后没反应<包括指令添加key＞
详情如下，有相同情况的大佬们
![Screenshot_20230608_211714_com sonelli juicessh](https://github.com/LlmKira/Openaibot/assets/129706123/0d6ddfba-4c68-4469-bec2-6ad9e30e6509)
![Screenshot_20230608_211830_com sonelli juicessh](https://github.com/LlmKira/Openaibot/assets/129706123/c43d9853-899f-4236-946c-2b94a52ffece)
服务器是华为云2h4gDebian镜像

**Comment by LtD0gE** [comment]
```toml
# Comment out which part you don't want to start
# 注释你不需要的部分

# QQ Bot
[Controller.QQ]
master = [114, 514] # QQ number
```

master改了吗
